name: METEOR
version: 0.0.1
main: org.domi.METEOR
author: Dominicus0830
website: "https://github.com/Dominicus0830?tab=repositories"
api-version: 1.20
description: 팔닥팔닥
depend: [CatFish]
commands:
  메테오영역설정:
    aliases: ["setMeteorArea", "메테오영역설정"]
    description: 메테오 영역을 설정합니다.
    permission: domi.setMeteorArea
    permission-message: "[OP] 권한이 없습니다."
  메테오:
    aliases: ["meteor", "메테오"]
    description: 메테오를 소환합니다.
    permission: domi.meteor
    permission-message: "[OP] 권한이 없습니다."
